# Generated by Django 5.1.6 on 2025-02-15 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_visualizacoes_data_hora'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultas',
            options={'verbose_name_plural': 'Consultas'},
        ),
        migrations.AlterModelOptions(
            name='pacientes',
            options={'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='tarefas',
            options={'verbose_name_plural': 'Tarefas'},
        ),
        migrations.AlterModelOptions(
            name='visualizacoes',
            options={'verbose_name_plural': 'Visualizações'},
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='queixa',
            field=models.CharField(choices=[('TDAH', 'TDAH'), ('D', 'Depressão'), ('A', 'Ansiedade'), ('TAG', 'Transtorno de Ansiedade Generalizada')], default='TDAH', max_length=4),
        ),
        migrations.AlterField(
            model_name='visualizacoes',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes', to='pacientes.consultas'),
        ),
    ]
